language: php

addons:
  chrome: stable

sudo: false

# Test main supported versions of PHP against latest WP.
php:
  - 5.6
  - 7.0
  - 7.1

env:
  - WP_VERSION=latest WP_MULTISITE=0

# Additional tests against stable PHP (min recommended version is 5.6) and past supported versions of WP
# and code coverage report.
matrix:
  fast_finish: true
  include:
  - php: 5.3
    dist: precise
  - php: 5.2
    dist: precise
  - php: 7.2
    env: WP_VERSION=latest WP_MULTISITE=0 RUN_PHPCS=1 RUN_E2E=1
  - php: 7.2
    env: WP_VERSION=latest WP_MULTISITE=0 RUN_CODE_COVERAGE=1
  allow_failures:
  - env: WP_VERSION=latest WP_MULTISITE=0 RUN_CODE_COVERAGE=1

before_script:
  - export PATH="$HOME/.composer/vendor/bin:$PATH"
  - bash tests/bin/install.sh woocommerce_test root '' localhost $WP_VERSION
  - bash tests/bin/travis.sh before

script:
  - bash tests/bin/phpunit.sh
  - bash tests/bin/phpcs.sh
  - mkdir ~/build/wordpress
  - chmod 755 ~/build/wordpress
  - sudo apt-get install nginx
  - sudo apt-get install php5-fpm
  - sudo cp ./tests/e2e-tests/config/travis_nginx.conf /etc/nginx/nginx.conf
  - sudo /etc/init.d/nginx restart
  - bash tests/e2e-tests/scripts/run-e2e.sh  

after_script:
  - bash tests/bin/travis.sh after
  - export NODE_CONFIG_DIR="./tests/e2e-tests/config"
  - ./tests/e2e-tests/scripts/wp-serverpilot-delete.js

# Specifies that Travis should create builds for master and release branches and also tags.
branches:
  only:
    - master
    - /^\d+\.\d+(\.\d+)?(-\S*)?$/
    - /^release\//
